// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Y6PkeCttG7NOOqLJ1ldJ2QUeCAaLKyE',
    appId: '1:551942555252:web:bd4b0079d7d882deb6b321',
    messagingSenderId: '551942555252',
    projectId: 'weatherwhiz-app',
    authDomain: 'weatherwhiz-app.firebaseapp.com',
    storageBucket: 'weatherwhiz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtfasJGr8IKfJOOiFukFd8FzJXpZxlPw',
    appId: '1:551942555252:android:f08af7096751a2f7b6b321',
    messagingSenderId: '551942555252',
    projectId: 'weatherwhiz-app',
    storageBucket: 'weatherwhiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6HYvXgOroxnPO6n-qYpVXUk5QjKbNzRY',
    appId: '1:551942555252:ios:6dbb97fe51271f77b6b321',
    messagingSenderId: '551942555252',
    projectId: 'weatherwhiz-app',
    storageBucket: 'weatherwhiz-app.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6HYvXgOroxnPO6n-qYpVXUk5QjKbNzRY',
    appId: '1:551942555252:ios:6dbb97fe51271f77b6b321',
    messagingSenderId: '551942555252',
    projectId: 'weatherwhiz-app',
    storageBucket: 'weatherwhiz-app.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Y6PkeCttG7NOOqLJ1ldJ2QUeCAaLKyE',
    appId: '1:551942555252:web:1a4af1bfb91d8398b6b321',
    messagingSenderId: '551942555252',
    projectId: 'weatherwhiz-app',
    authDomain: 'weatherwhiz-app.firebaseapp.com',
    storageBucket: 'weatherwhiz-app.firebasestorage.app',
  );
}
